version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'blog-api'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql